theme: jekyll-theme-minimal
title: Test Informed Learning with Examples
description: Repository with assignments using the Test Informed Learning with Examples (TILE) method to integrate testing into existing programming courses for free.
author: Niels Doorn, Tanja Vos, Beatriz Marín
show_downloads: false
logo: TILE_logo.png
url: "https://tile-repository.github.io" # the base hostname & protocol for your site
github:
  is_project_page: false
  is_user_page: false
kramdown:
  auto_ids: true
  toc_levels: 1..3