theme: jekyll-theme-minimal
title: Test Informed Learning with Examples
description: A repository with assignments that are using the Test Informed Learning with Examples (TILE) method to integrate testing into existing programming courses.
author: Niels Doorn, Tanja Vos, Beatriz Marin
show_downloads: false
logo: TILE_logo.png
github:
  is_project_page: true
kramdown:
  auto_ids: true
  toc_levels: 1..2
gems: [jekyll-mermaid]
mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js'