theme: jekyll-theme-slate
title: TILES
description: Nifty assignments that are using the Test Informed Learning by Example (TILE) method to improve testing.
author: Niels Doorn
github:
  is_project_page: false