# theme: jekyll-theme-slate
theme: jekyll-theme-minimal
title: TILES
description: Nifty assignments that are using the Test Informed Learning by Example (TILE) method to improve testing.
author: Niels Doorn
show_downloads: false
logo: TILE_logo.png
github:
  is_project_page: false
