theme: jekyll-theme-minimal
title: TILE
description: Nifty assignments that are using the Test Informed Learning by Example (TILE) method to integrate testing into programming education.
author: Niels Doorn, Tanja Vos, Beatriz Marin
show_downloads: false
logo: TILE_logo.png
github:
  is_project_page: false
