# This workflow produces an index and pushes it to the repository.

name: process meta data

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEVOPS_DIR: devops  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check-out devops repository
        uses: actions/checkout@v2
        with:
          repository: TILE-repository/devops
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DEVOPS_DIR }}

      - name: Hello World
        run: python ${{ env.DEVOPS_DIR }}/process_meta_data.py
        shell: sh